[package]
name = "uniffi-example-documentation"
edition = "2021"
version = "0.23.0"
license = "MPL-2.0"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
name = "uniffi_documentation"

[dependencies]
uniffi = { path = "../../uniffi"}

[build-dependencies]
uniffi = { path = "../../uniffi", features = ["build"] }

[dev-dependencies]
uniffi = { path = "../../uniffi", features = ["bindgen-tests"] }
